# Rcpp入門

RからC++を利用するには、いくつか方法がありますが、「Rcpp」パッケージを使うのが簡単な方法の一つだと思います。「RcppArmadillo」、「RcppEigen」などのパッケージを併用することで、C++内のコーディングも容易になります。

## 「Rcpp」パッケージについて

RとC++のシームレスな統合を提供するC++クラスとR関数を提供します。多くのRデータ型とオブジェクトは、C++に相当するものにマッピングすることができます。新しいコードの作成やサードパーティのライブラリとの統合を容易にします。 

## 「RcppArmadillo」と「RcppEigen」パッケージについて

「Armadillo」と「Eigen」は、テンプレート型のC++線形代数ライブラリです。整数、浮動小数点数、複素数などの行列を扱うクラスや、統計関数をサポートしています。

それぞれの特徴としては、一概には言えませんが、

* 処理速度は、「Eigen」が速い
* 記述は、「Armadillo」が容易

「RcppArmadillo」と「RcppEigen」パッケージは、「Rcpp」から上記ライブラリを利用するパッケージです。

パッケージには、上記ライブラリのヘッダーファイルが含まれていますので、それ自体をインストールする必要はありません。ただし、C++のコンパイルが必要になりますので、先に「Rtools」をインストールしてください。

## パッケージのインストール 

まず、「[Rtools](https://cran.r-project.org/bin/windows/Rtools/)」をインストールして下さい。

その後、管理者権限でRを起動し、以下を実行してください。※1

----

```
install.packages("Rcpp")
install.packages("RcppArmadillo")
install.packages("RcppEigen")
```

----

「RcppArmadillo」パッケージのインストール中に、「パッケージのソースからインストールを行いますか?」と聞かれる場合がありますが、「y」で実行してください。

インストール終了後、「Jupyter Notebook」は再起動してください。

※ バージョンによっては正常に動作しない場合があります。私が試した環境は、

* R version 3.4.1
* Rcpp 0.12.12
* RcppArmadillo 0.7.960.1.2
* RcppEigen 0.3.3.3.0

## 簡単なサンプル（RcppArmadillo）

In [1]:
# パッケージの読込み
library(Rcpp)
library(RcppArmadillo)

# C+11にてコンパイルします（ラムダ式などが利用できます。うまくいかない場合はコメントアウトしてみてください。）
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")

In [2]:
# C++のコード
code <- '
arma::mat PlusOneArma(arma::mat src)
{
    // 行列の全ての要素に加算
    arma::mat dst = src + 1;

    return dst;
}
'

# コンパイルとリンクを行います（少し時間がかかります）
cppPlusOneArma <- cppFunction(code, depends="RcppArmadillo")

In [3]:
src0 <- matrix(1:12, nrow=3)
print(src0)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [4]:
dst0 <- cppPlusOneArma(src0)
print(dst0)

     [,1] [,2] [,3] [,4]
[1,]    2    5    8   11
[2,]    3    6    9   12
[3,]    4    7   10   13


## 簡単なサンプル（RcppEigen） 

In [5]:
# パッケージの読込み
library(Rcpp)
library(RcppEigen)

# C+11にてコンパイルします（ラムダ式などが利用できます。うまくいかない場合はコメントアウトしてみてください。）
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")


Attaching package: 'RcppEigen'

The following objects are masked from 'package:RcppArmadillo':

    fastLm, fastLmPure



↑ エラーではありませんよ。

In [6]:
# C++のコード
code <- '
Eigen::MatrixXd PlusOneEigen(Eigen::MatrixXd src)
{
    // 行列の全ての要素に加算
    Eigen::MatrixXd dst = src.array() + 1.0;

    return dst;
}
'

# コンパイルとリンクを行います（少し時間がかかります）
cppPlusOneEigen <- cppFunction(code, depends="RcppEigen", includes=c("#include <RcppEigen.h>"))

↑ `depends="RcppEigen"`と設定していれば、`includes=c("#include <RcppEigen.h>")`は不要のように思いますが、私の環境では必要でした。

In [7]:
src1 <- matrix(as.numeric(1:12), nrow=3) #整数ではなく浮動小数点にすること
print(src1)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [8]:
dst1 <- cppPlusOneEigen(src1)
print(dst1)

     [,1] [,2] [,3] [,4]
[1,]    2    5    8   11
[2,]    3    6    9   12
[3,]    4    7   10   13


----
※1  
「Jupyter Notebook」で利用するのであれば、「[パッケージを読み込めないエラーについて](https://nbviewer.jupyter.org/github/waku-take-a/JupyterTips/blob/master/Error_occurred_in_library_function.ipynb)」の「パッケージのインストール先を変更する」を行ってください。

----
[ホームへ](https://waku-take-a.github.io/index.html)  
[↑Rの記事Topへ](https://waku-take-a.github.io/R.html)  

※  
上記のipynbファイル等は、[こちらに](https://github.com/WAKU-TAKE-A/RTips)あります。  
解凍後、`The jupyter notebook`にアップロードすれば、ローカルな環境で実行することも、編集することもできます。

<(_ _)>

★★★responsive_ja★★★